source 'https://rubygems.org'

ruby '2.2.1'

gem 'rails', '~> 4.2.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '~> 2.7.0'
gem 'coffee-rails', '~> 4.1.0'

gem 'jquery-rails', '~> 4.0.0'
gem 'turbolinks', '~> 2.5.0'
gem 'jbuilder', '~> 2.2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'less-rails', '~> 2.6.0'
gem 'twitter-bootstrap-rails', '~> 3.2.0'
gem 'therubyracer', '~> 0.12.0'

gem 'omniauth', '~> 1.2.0'
gem 'omniauth-twitter', '~> 1.1.0'
gem 'settingslogic', '~> 2.0.0'

gem "oauth", '~> 0.4.0'
gem 'twitter', '~> 5.14.0'
gem "tweetstream", '~> 2.6.0'

gem "sprockets", '2.12.3'

gem 'mysql2'

gem 'whenever', '~> 0.9.0', :require => false

group :development, :test do
  gem 'rb-readline'
  gem 'rspec', '~> 3.0'
  gem 'rspec-rails', '~> 3.0'
  gem 'better_errors', '~> 2.0'
  gem 'byebug', '~> 4.0'
  gem 'web-console', '~> 2.0'
  gem 'spring', '~> 1.0'
  gem 'capistrano', '~> 3.0'
  gem 'capistrano-rails', '~> 1.0'
  gem 'capistrano-rbenv', '~> 2.0'
  gem 'capistrano-bundler', '~> 1.0'
  gem 'capistrano3-unicorn', '~> 0.1'
end

group :test do
  gem 'test-unit', '~> 3.0'
  gem 'minitest', '~> 5.0'
  gem 'selenium-webdriver', ' ~> 2.0'
  gem 'capybara', '~> 2.0'
  gem 'shoulda-matchers', '~> 2.0'
  gem 'rails-erd'
  # gem 'coveralls', require: false
end

group :production, :staging do
  gem 'unicorn'
end
