default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: password
  timeout: 5000
development:
  <<: *default
  database: harmox
  socket: /private/tmp/mysql.sock
test:
  <<: *default
  database: harmox
production:
  <<: *default
  database: harmox
  socket: /var/lib/mysql/mysql.sock
